### ISSUE TITLE
Deal with "Reflect.getMetadata is not a function"

### ISSUE THREAD

**Issue by douglasnaphas** [secret-traitor/secret-traitor#24]
This appears in CloudWatch after I try to hit our canary endpoint.

```
$ curl https://8c99q6ims2.execute-api.us-east-1.amazonaws.com/prod/canary
{"message": "Internal server error"}
```

```
{
    "errorType": "TypeError",
    "errorMessage": "Reflect.getMetadata is not a function",
    "stack": [
        "TypeError: Reflect.getMetadata is not a function",
        "    at Object.findType (/var/task/node_modules/type-graphql/dist/helpers/findType.js:9:35)",
        "    at /var/task/node_modules/type-graphql/dist/decorators/Field.js:16:53",
        "    at Object.__decorate (/var/task/node_modules/tslib/tslib.js:96:114)",
        "    at Object.<anonymous> (/var/task/src/graphql/Player/Player.js:8:9)",
        "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
        "    at Module.load (internal/modules/cjs/loader.js:879:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Module.require (internal/modules/cjs/loader.js:903:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)"
    ]
}
```

**Comment by dan-muller** [comment]
@douglasnaphas why are we importing `src/server/index` instead of `src/index/`? The top-level index contains the import for reflect-metadata which is needed for that library to work correctly.

**Comment by douglasnaphas** [comment]
> @douglasnaphas why are we importing `src/server/index` instead of `src/index/`? The top-level index contains the import for reflect-metadata which is needed for that library to work correctly.

I moved the `reflect-metadata` import to `src/server/index` just now.

`src/index` does things that are needed in local development, but not in production:

https://github.com/secret-traitor/secret-traitor/commit/0bd7f4020e0341fbf3b3deb04cc0132f4b8a6ecd

**Comment by dan-muller** [comment]
I dont think that is a good idea, it seems like we are just trying to move things around until they work. I am going to take a different approach to creating the lambda handlers

**Comment by douglasnaphas** [comment]
https://github.com/secret-traitor/secret-traitor/commit/0bd7f4020e0341fbf3b3deb04cc0132f4b8a6ecd seems to have addressed the immediate bug (`"Reflect.getMetadata is not a function"`).

If the Lambda handlers were the issue, the request would not be getting through and invoking the application code.

**Comment by dan-muller** [comment]
closing this issue since the `reflect-metadata` issue is resolved
